import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main()=>runApp(const PHFApp());
class PHFApp extends StatelessWidget{const PHFApp({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'PHF',theme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.indigo),home:const Home());}
class Crew{String name,phone;Crew(this.name,this.phone);Map<String,dynamic> j()=>{'n':name,'p':phone};factory Crew.f(Map<String,dynamic> x)=>Crew(x['n']??'',x['p']??'');}
const roles=['Candid','Cinematographer','T. Photo','T. Video','Drone','Helper'];
class Ev{String id,client,phone,venue,time,notes;DateTime date;Map<String,Crew?> crew;Ev({required this.id,required this.client,required this.phone,required this.venue,required this.time,required this.notes,required this.date,required this.crew});Map<String,dynamic> j()=>{'id':id,'client':client,'phone':phone,'venue':venue,'time':time,'notes':notes,'date':date.toIso8601String(),'crew':crew.map((k,v)=>MapEntry(k,v?.j()))};factory Ev.f(Map<String,dynamic>x){final r=Map<String,dynamic>.from(x['crew']??{});return Ev(id:x['id'],client:x['client']??'',phone:x['phone']??'',venue:x['venue']??'',time:x['time']??'',notes:x['notes']??'',date:DateTime.parse(x['date']),crew:{for(final e in r.entries)e.key=e.value==null?null:Crew.f(Map<String,dynamic>.from(e.value))});}}
class Home extends StatefulWidget{const Home({super.key});@override State<Home> createState()=>_Home();}
class _Home extends State<Home>{DateTime sel=DateTime.now(),mon=DateTime(DateTime.now().year,DateTime.now().month);List<Ev> ev=[];List<Crew> team=[];@override void initState(){super.initState();load();}Future<void>load()async{final p=await SharedPreferences.getInstance();setState(()=>{ev=(p.getStringList('e')??[]).map((x)=>Ev.f(jsonDecode(x))).toList(),team=(p.getStringList('t')??[]).map((x)=>Crew.f(jsonDecode(x))).toList()});}Future<void>save()async{final p=await SharedPreferences.getInstance();await p.setStringList('e',ev.map((x)=>jsonEncode(x.j())).toList());await p.setStringList('t',team.map((x)=>jsonEncode(x.j())).toList());}List<Ev> day(DateTime d)=>ev.where((x)=>x.date.year==d.year&&x.date.month==d.month&&x.date.day==d.day).toList();String mn(int m)=>const['','January','February','March','April','May','June','July','August','September','October','November','December'][m];
@override Widget build(BuildContext c){final first=DateTime(mon.year,mon.month,1),days=DateTime(mon.year,mon.month+1,0).day,start=first.weekday%7;return Scaffold(appBar:AppBar(title:const Text('PHF',style:TextStyle(fontWeight:FontWeight.bold)),actions:[IconButton(onPressed:teamPage,icon:const Icon(Icons.people)),IconButton(onPressed:()=>setState(()=>{sel=DateTime.now(),mon=DateTime(DateTime.now().year,DateTime.now().month)}),icon:const Icon(Icons.today))]),floatingActionButton:FloatingActionButton.extended(onPressed:()=>form(null,sel),icon:const Icon(Icons.add),label:const Text('Event')),body:Column(children:[Row(children:[IconButton(onPressed:()=>setState(()=>mon=DateTime(mon.year,mon.month-1)),icon:const Icon(Icons.chevron_left)),Expanded(child:Center(child:Text('${mn(mon.month)} ${mon.year}',style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold)))),IconButton(onPressed:()=>setState(()=>mon=DateTime(mon.year,mon.month+1)),icon:const Icon(Icons.chevron_right))]),Row(children:['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((x)=>Expanded(child:Center(child:Text(x,style:const TextStyle(fontWeight:FontWeight.bold,fontSize:11))))).toList()),Expanded(child:GridView.builder(padding:const EdgeInsets.all(8),itemCount:((start+days+6)~/7)*7,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:7,childAspectRatio:.8),itemBuilder:(_,i){if(i<start||i>=start+days)return const SizedBox();final d=DateTime(mon.year,mon.month,i-start+1),list=day(d),s=d.year==sel.year&&d.month==sel.month&&d.day==sel.day;return InkWell(onTap:()=>setState(()=>sel=d),child:Container(margin:const EdgeInsets.all(2),padding:const EdgeInsets.all(3),decoration:BoxDecoration(color:s?Theme.of(c).colorScheme.primaryContainer:Colors.white,borderRadius:BorderRadius.circular(9),border:Border.all(color:s?Theme.of(c).colorScheme.primary:Colors.black12)),child:Column(children:[Text('${d.day}',style:const TextStyle(fontWeight:FontWeight.bold)),if(list.isNotEmpty)Container(margin:const EdgeInsets.only(top:3),padding:const EdgeInsets.all(2),decoration:BoxDecoration(color:Theme.of(c).colorScheme.primary,borderRadius:BorderRadius.circular(4)),child:Text('${list.length} • ${list.first.client}',overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white,fontSize:8)))])));})),Container(color:Colors.white,padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${sel.day} ${mn(sel.month)} ${sel.year}',style:const TextStyle(fontWeight:FontWeight.bold)),...day(sel).map((e)=>ListTile(contentPadding:EdgeInsets.zero,title:Text(e.client,style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('${e.venue} • ${e.time}'),onTap:()=>form(e,sel)))]))]));}
Future<void>form(Ev? old,DateTime d)async{final x=await Navigator.push<Ev>(context,MaterialPageRoute(builder:(_)=>FormPage(old,d,team,ev)));if(x!=null){setState((){final i=ev.indexWhere((z)=>z.id==x.id);if(i<0)ev.add(x);else ev[i]=x;sel=x.date;mon=DateTime(x.date.year,x.date.month);});save();}}Future<void>teamPage()async{final x=await Navigator.push<List<Crew>>(context,MaterialPageRoute(builder:(_)=>TeamPage(team)));if(x!=null){setState(()=>team=x);save();}}
}
class FormPage extends StatefulWidget{final Ev? old;final DateTime initial;final List<Crew> team;final List<Ev> all;const FormPage(this.old,this.initial,this.team,this.all,{super.key});@override State<FormPage> createState()=>_Form();}
class _Form extends State<FormPage>{late DateTime d;final cs=List.generate(5,(_)=>TextEditingController());late Map<String,Crew?> crew;@override void initState(){super.initState();d=widget.old?.date??widget.initial;crew={for(final r in roles)r:null};if(widget.old!=null){final e=widget.old!;cs[0].text=e.client;cs[1].text=e.phone;cs[2].text=e.venue;cs[3].text=e.time;cs[4].text=e.notes;crew.addAll(e.crew);}}@override void dispose(){for(final x in cs)x.dispose();super.dispose();}Future<void>pick()async{final x=await showDatePicker(context:context,initialDate:d,firstDate:DateTime(2020),lastDate:DateTime(2035));if(x!=null)setState(()=>d=x);}void done(){if(cs[0].text.trim().isEmpty)return;Navigator.pop(context,Ev(id:widget.old?.id??DateTime.now().microsecondsSinceEpoch.toString(),client:cs[0].text.trim(),phone:cs[1].text.trim(),venue:cs[2].text.trim(),time:cs[3].text.trim(),notes:cs[4].text.trim(),date:d,crew:crew));}
@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(widget.old==null?'Add Event':'Edit Event'),actions:[IconButton(onPressed:done,icon:const Icon(Icons.check))]),body:ListView(padding:const EdgeInsets.all(14),children:[ListTile(tileColor:Colors.white,leading:const Icon(Icons.calendar_month),title:const Text('Event date'),subtitle:Text('${d.day}/${d.month}/${d.year}'),onTap:pick),...['Client / Couple name','Client phone','Venue','Time','Notes'].asMap().entries.map((e)=>Padding(padding:const EdgeInsets.only(top:9),child:TextField(controller:cs[e.key],maxLines:e.key==4?3:1,keyboardType:e.key==1?TextInputType.phone:null,decoration:InputDecoration(labelText:e.value,border:const OutlineInputBorder())))),const Padding(padding:EdgeInsets.only(top:18,bottom:6),child:Text('TEAM ASSIGNMENT',style:TextStyle(fontWeight:FontWeight.bold)),...roles.map((r)=>Card(child:ListTile(title:Text(r),subtitle:Text(crew[r]==null?'Not assigned':'${crew[r]!.name} • ${crew[r]!.phone}'),trailing:DropdownButton<Crew?>(value:crew[r],hint:const Text('Assign'),items:[const DropdownMenuItem(value:null,child:Text('None')), ...widget.team.map((p)=>DropdownMenuItem(value:p,child:Text(p.name)))],onChanged:(v)=>setState(()=>crew[r]=v)))))]));}
class TeamPage extends StatefulWidget{final List<Crew> team;const TeamPage(this.team,{super.key});@override State<TeamPage> createState()=>_Team();}
class _Team extends State<TeamPage>{late List<Crew> t;@override void initState(){super.initState();t=List.of(widget.team);}Future<void>add()async{final n=TextEditingController(),p=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('Add team member'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Name')),TextField(controller:p,decoration:const InputDecoration(labelText:'Contact number'),keyboardType:TextInputType.phone)]),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Add'))]));if(ok==true&&n.text.isNotEmpty)setState(()=>t.add(Crew(n.text,p.text)));n.dispose();p.dispose();}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('PHF Team'),actions:[IconButton(onPressed:()=>Navigator.pop(context,t),icon:const Icon(Icons.check))]),floatingActionButton:FloatingActionButton(onPressed:add,child:const Icon(Icons.add)),body:t.isEmpty?const Center(child:Text('No team members. Tap + to add.')):ListView.builder(itemCount:t.length,itemBuilder:(_,i)=>ListTile(leading:const CircleAvatar(child:Icon(Icons.person)),title:Text(t[i].name),subtitle:Text(t[i].phone),trailing:IconButton(onPressed:()=>setState(()=>t.removeAt(i)),icon:const Icon(Icons.delete)))));}
